spring:
  application:
    name: springboot-demo

  banner:
    location: classpath:banner/banner.txt

  profiles:
    active: local

server:
  port: 8006

horse:
  owner: 吕布
  nickName: 赤兔

#debug: true