spring:
  redis:
    database: 0
    # Redis服务器地址
    host: 192.168.6.232
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000
  data:
    mongodb:
      database: db_terminal
      host: 192.168.6.160
      port: 27017
  datasource:
  #数据库地址，测试人员自己配置
    url: jdbc:mysql://192.168.6.232:3306/db_terminal?Unicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=PRC
    driverClassName: com.mysql.jdbc.Driver
    #用户
    username: root
    #密码
    password: 123456
    filters:  stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    initialSize:  2
    minIdle: 1
    maxActive: 4
    maxWait: 60000
#eureka配置，测试人员自己配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://test1.mysirui.com:8761/eureka/,http://test2.mysirui.com:8761/eureka/,http://test3.mysirui.com:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
#swagger:
#  enable: true

# hystrix 线程策略，次可以访问到父线程的上下文
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000000
        timeout:
          enabled: false




