spring:
  application:
    name: springboot-demo

  banner:
    location: classpath:banner/banner.txt

  mvc:
    favicon:
      enabled: false

  profiles:
    active: local

#  messages:
#    basename: messages
#    encoding: UTF-8

server:
  port: 8006
#  servlet:
#    context-path: /demo

horse:
  owner: 吕布
  nickName: 赤兔


logging:
  level:
    com.demo: debug
#    root: debug
#  config: classpath:logback.xml
#  config: classpath:log4j.properties

#debug: true
