spring:
  # redis数据库（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
#  data:
#    mongodb:
#      trip:
#        database: db_terminal
#        host: 192.168.6.160
#        port: 27017
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_terminal?Unicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: fastgo123
    filters:  stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    initialSize:  2
    minIdle: 1
    maxActive: 4
    maxWait: 60000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html


swagger:
  enable: true

#日志配置

mybatis:
  localXmlPath: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.demo.springboot.entity.po
    
# hystrix 线程策略，次可以访问到父线程的上下文
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 200000