spring:
  application:
    name: springboot-demo

  banner:
    location: classpath:banner/banner.txt

  profiles:
    active: dev

server:
  port: 8006

horse:
  owner: 吕布
  nickName: 赤兔


logging:
  level:
    com.demo: debug
#    root: debug
#  config: classpath:logback.xml
#  config: classpath:log4j.properties

#debug: true
